version: "3"
services:
  backend:
    volumes: 
      - ./backend/:/backend
    tty: true
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - 127.0.0.1:8080:8080
  frontend:
    volumes:
      - ./web/:/frontend
    tty: true 
    build:
      context: ./web 
      dockerfile: ./Dockerfile
    ports:
      - 127.0.0.1:3000:3000